services:
  openproject:
    image: openproject/openproject:15
    container_name: openproject
    ports:
      - 85:80
    restart: unless-stopped
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=${OPENPROJECT_SECRET_KEY_BASE}
      - OPENPROJECT_HOST__NAME=${OPENPROJECT_HOST__NAME}
      - OPENPROJECT_HTTPS=${OPENPROJECT_HTTPS}
      - OPENPROJECT_DEFAULT__LANGUAGE=${OPENPROJECT_DEFAULT__LANGUAGE}
    volumes:
      - ./pgdata:/var/openproject/pgdata
      - ./assets:/var/openproject/assets
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: "2.0" # Limita a 2 CPU
          memory: "4g" # Limita a 3 GB de memoria

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openproject_backup
    environment:
      - SMB_SERVER=${SMB_SERVER}
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASS}
      - SMB_SHARE=${SMB_SHARE}
      - BACKUP_FREQ=${BACKUP_FREQ}
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./backups:/backups
      - ./pgdata:/var/openproject/pgdata
      - ./assets:/var/openproject/assets
    restart: always
    depends_on:
      - openproject
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limita a 0.5 CPU
          memory: "256M" # Limita a 256 MB de memoria
